In [3]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [4]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
flat = arr.flatten()

In [6]:
flat


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[0]

1

In [8]:
flat[0:4]

array([1, 2, 3, 4])

In [9]:
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [13]:
sliced=flat[:3]
sliced[0]=99999
print(flat)

[99999     2     3     4     5     6     7     8     9    10    11    12]


In [15]:
copy=flat[:3].copy()    #This is not slice it's copy
copy[1]=6666
print(flat)

[99999     2     3     4     5     6     7     8     9    10    11    12]
[99999  6666     3]


In [16]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [17]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]
