In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])

In [4]:
np.mean(arr)

3.0

In [5]:
np.max(arr)


5

In [6]:
np.min(arr)


1

In [7]:
np.std(arr)

1.4142135623730951

In [9]:
np.var(arr)

2.0

In [10]:
np.sum(arr)

15

In [12]:
np.prod(arr)

120

In [13]:
np.median(arr)

3.0

In [14]:
np.percentile(arr,50)

3.0

In [17]:
np.argmin(arr) #it's give index

0

In [18]:
np.argmax(arr)

4

In [19]:
np.unique(arr)

array([1, 2, 3, 4, 5])

In [20]:
np.diff(arr)

array([1, 1, 1, 1])

In [21]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])

In [23]:
np.linspace(1,4,3)

array([1. , 2.5, 4. ])

In [24]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [25]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])