## Numpy
learn about Numpy 

In [2]:
import numpy as np

#### creating arrays from list


In [3]:
arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[4,5,6]])

print("1D-Array : ",arr_1d)
print("2D-Array :\n ",arr_2d)

1D-Array :  [1 2 3]
2D-Array :
  [[1 2 3]
 [4 5 6]]


### Python List VS Numpy Arrays

In [4]:
list = [1,2,3]
print("python list multiplication : ",list*2)

arr = np.array(list)
print("python array multiplication : ",arr*2)  #Element Wise Multiplication



python list multiplication :  [1, 2, 3, 1, 2, 3]
python array multiplication :  [2 4 6]


In [9]:
import time as time
start = time.time()
list1=[i*2 for i in range(100000000)]
print("Time taken to list : ",time.time()-start)

arr1 = np.arange(100000000) * 2 
print("Time taken to Array : ",time.time()-start)


Time taken to list :  4.362883806228638
Time taken to Array :  4.7685627937316895


### Creating Arrays from Scratch

In [19]:
zeros = np.zeros((2,3))
print(zeros,"\n")

ones = np.ones((2,3))
print(ones,"\n")

full = np.full((2,3),7) #Create Arry with Fill value 7.
print(full,"\n")

random = np.random.random((2,3)) #Creating Array with random value
print(random,"\n")

squence =  np.arange(0,10)
print(squence,"\n")


arange = np.arange(1,10,2) #(start,end,step) it will skip one by one value.
print(arange,"\n")

line_space = np.linspace(1,2,5) #(start,stop,supportIndex) Divide 1 to 2 into 5 parts evenly.
print(line_space,"\n")

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[7 7 7]
 [7 7 7]] 

[[0.09312466 0.79427183 0.88351005]
 [0.36633343 0.33919989 0.58681525]] 

[0 1 2 3 4 5 6 7 8 9] 

[1 3 5 7 9] 

[1.   1.25 1.5  1.75 2.  ] 

