In [1]:
import numpy as np

In [8]:
arr= np.array([1,2,3])
arr2=np.array([[1,2,3],[5,6,7]])

In [12]:
print("1D : ",arr)
print("2D:",arr2)

1D :  [1 2 3]
2D: [[1 2 3]
 [5 6 7]]


In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [20]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
myarr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
print("Shape is     : ",myarr.shape)
print("Size is      : ",myarr.size)
print("Dimensions is: ",myarr.ndim)
print("Type is      : ",myarr.dtype)

Shape is     :  (4, 3)
Size is      :  12
Dimensions is:  2
Type is      :  int32


In [33]:
myarr= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='float32')
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [36]:
n = myarr.astype('float64')

In [37]:
n.dtype

dtype('float64')

In [39]:
myarr.dtype

dtype('float32')

In [40]:
reshaped=myarr.reshape((3,4))

In [41]:
reshaped


array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [43]:
myarr.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
      dtype=float32)